"""cb report - Structured vulnerability report generator."""
import argparse
import json
import os
import sys
import time

from cb.output import add_output_args, make_formatter, load_piped_input


# CVSS estimation lookup: (severity, vector) -> score
CVSS_TABLE = {
    ("high", "remote"): 9.8,
    ("high", "file"): 8.8,
    ("high", "file_based"): 8.8,
    ("high", "ipc"): 8.8,
    ("high", "local"): 7.8,
    ("high", "kernel"): 9.0,
    ("high", "unknown"): 7.8,
    ("medium", "remote"): 6.5,
    ("medium", "file"): 5.5,
    ("medium", "file_based"): 5.5,
    ("medium", "ipc"): 5.5,
    ("medium", "local"): 5.5,
    ("medium", "kernel"): 6.5,
    ("medium", "unknown"): 5.5,
    ("low", "remote"): 3.3,
    ("low", "file"): 3.3,
    ("low", "file_based"): 3.3,
    ("low", "ipc"): 3.3,
    ("low", "local"): 3.3,
    ("low", "kernel"): 3.3,
    ("low", "unknown"): 3.3,
}


TEMPLATE_BUGBOUNTY = """# {title}

**Severity:** {risk_level_upper} — CVSS {cvss}
**Type:** {cwe_summary}
**Target:** `{binary}`
**Date:** {date}

## Summary
{executive_summary}

## Findings

{findings_section}

## Attack Chain
{attack_chain_section}

## Steps to Reproduce
{steps_section}

## Impact
{impact_section}

## Root Cause
{root_cause_section}

## Recommended Fix
{recommendations_section}

---
*Generated by {author}*
"""

TEMPLATE_INTERNAL = """# {title}

## Executive Summary
{executive_summary}

## Target Information
| Field | Value |
|-------|-------|
| Binary | `{binary}` |
| Date | {date} |
| Author | {author} |
| CWE | {cwe_summary} |

## Findings Overview

| # | Type | Severity | CVSS | CWE | Description |
|---|------|----------|------|-----|-------------|
{findings_table}

## Detailed Findings

{findings_detail}

## Root Cause Analysis
{root_cause_section}

## Recommendations
{recommendations_section}

---
*Generated by {author}*
"""

# ---------------------------------------------------------------------------
# HTML templates
# ---------------------------------------------------------------------------

_HTML_STYLE = """\
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
         max-width: 960px; margin: 0 auto; padding: 2rem; color: #1a1a2e; background: #fafafa; }
  h1 { border-bottom: 3px solid #16213e; padding-bottom: 0.5rem; }
  h2 { color: #16213e; margin-top: 2rem; }
  h3 { color: #0f3460; }
  table { border-collapse: collapse; width: 100%; margin: 1rem 0; }
  th, td { border: 1px solid #ddd; padding: 0.5rem 0.75rem; text-align: left; }
  th { background: #16213e; color: white; }
  tr:nth-child(even) { background: #f2f2f2; }
  .severity-high { color: #fff; background: #e74c3c; padding: 2px 8px; border-radius: 3px; font-weight: bold; }
  .severity-medium { color: #fff; background: #e67e22; padding: 2px 8px; border-radius: 3px; font-weight: bold; }
  .severity-low { color: #fff; background: #27ae60; padding: 2px 8px; border-radius: 3px; font-weight: bold; }
  .severity-unknown { color: #fff; background: #95a5a6; padding: 2px 8px; border-radius: 3px; }
  .finding-card { border: 1px solid #ddd; border-radius: 6px; padding: 1rem; margin: 1rem 0;
                  background: white; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
  .finding-card h3 { margin-top: 0; }
  .summary-box { background: #16213e; color: white; padding: 1.5rem; border-radius: 8px; margin: 1rem 0; }
  .summary-box h2 { color: white; margin-top: 0; }
  .metric { display: inline-block; text-align: center; margin: 0 1.5rem 0 0; }
  .metric-value { font-size: 2rem; font-weight: bold; }
  .metric-label { font-size: 0.85rem; opacity: 0.8; }
  code { background: #eee; padding: 2px 6px; border-radius: 3px; font-size: 0.9em; }
  pre { background: #2d2d2d; color: #f8f8f2; padding: 1rem; border-radius: 6px; overflow-x: auto; }
  .recommendations li { margin: 0.5rem 0; }
  .chart-container { margin: 1rem 0; }
  @media print { body { max-width: 100%; } .summary-box { background: #333; } }
  @media (max-width: 600px) { body { padding: 1rem; } .metric { display: block; margin: 0.5rem 0; } }
</style>
"""

HTML_BUGBOUNTY = """\
<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
{style}
</head>
<body>
<h1>{title}</h1>
<div class="summary-box">
<h2>Summary</h2>
<p>{executive_summary}</p>
<div class="metric"><div class="metric-value">{max_cvss}</div><div class="metric-label">Max CVSS</div></div>
<div class="metric"><div class="metric-value severity-{risk_level}">{risk_level_upper}</div><div class="metric-label">Risk Level</div></div>
</div>
<h2>Target</h2>
<table><tr><th>Binary</th><td><code>{binary}</code></td></tr>
<tr><th>Date</th><td>{date}</td></tr>
<tr><th>CWE</th><td>{cwe_summary}</td></tr></table>
<h2>Findings Distribution</h2>
<div class="chart-container">{chart_svg}</div>
<h2>Findings</h2>
{findings_html}
<h2>Attack Chain</h2>
<p>{attack_chain_html}</p>
<h2>Steps to Reproduce</h2>
<ol>{steps_html}</ol>
<h2>Impact</h2>
<p>{impact_section}</p>
<h2>Root Cause</h2>
<p>{root_cause_html}</p>
<h2>Recommended Fix</h2>
<ul class="recommendations">{recommendations_html}</ul>
<hr><p><em>Generated by {author}</em></p>
</body></html>
"""

HTML_INTERNAL = """\
<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
{style}
</head>
<body>
<h1>{title}</h1>
<div class="summary-box">
<h2>Executive Summary</h2>
<p>{executive_summary}</p>
<div class="metric"><div class="metric-value">{max_cvss}</div><div class="metric-label">Max CVSS</div></div>
<div class="metric"><div class="metric-value">{high_count}</div><div class="metric-label">High</div></div>
<div class="metric"><div class="metric-value">{med_count}</div><div class="metric-label">Medium</div></div>
<div class="metric"><div class="metric-value">{low_count}</div><div class="metric-label">Low</div></div>
</div>
<h2>Target Information</h2>
<table><tr><th>Binary</th><td><code>{binary}</code></td></tr>
<tr><th>Date</th><td>{date}</td></tr><tr><th>Author</th><td>{author}</td></tr>
<tr><th>CWE</th><td>{cwe_summary}</td></tr></table>
<h2>Findings Distribution</h2>
<div class="chart-container">{chart_svg}</div>
<h2>Findings Overview</h2>
<table><tr><th>#</th><th>Type</th><th>Severity</th><th>CVSS</th><th>CWE</th><th>Description</th></tr>
{findings_table_html}
</table>
<h2>Detailed Findings</h2>
{findings_html}
<h2>Root Cause Analysis</h2>
<p>{root_cause_html}</p>
<h2>Recommendations</h2>
<ul class="recommendations">{recommendations_html}</ul>
<hr><p><em>Generated by {author}</em></p>
</body></html>
"""

HTML_BRIEF = """\
<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title} — {date}</title>
{style}
</head>
<body>
<h1>{title} &mdash; {date}</h1>
<p>Target: <code>{binary}</code></p>
<div class="chart-container">{chart_svg}</div>
<ol>{findings_brief_html}</ol>
<p>Risk: <span class="severity-{risk_level}">{risk_level_upper}</span> | Max CVSS: <strong>{max_cvss}</strong></p>
<hr><p><em>{author}</em></p>
</body></html>
"""

TEMPLATE_BRIEF = """# {title} — {date}

Target: `{binary}`

{findings_brief}

Risk: **{risk_level}** | Max CVSS: **{max_cvss}**

---
*{author}*
"""


# CWE mapping: finding type -> (CWE ID, name)
CWE_MAP = {
    "overflow": ("CWE-120", "Buffer Copy without Checking Size of Input"),
    "buffer_overflow": ("CWE-120", "Buffer Copy without Checking Size of Input"),
    "format_string": ("CWE-134", "Use of Externally-Controlled Format String"),
    "integer_overflow": ("CWE-190", "Integer Overflow or Wraparound"),
    "race_condition": ("CWE-362", "Concurrent Execution using Shared Resource"),
    "use_after_free": ("CWE-416", "Use After Free"),
    "double_free": ("CWE-415", "Double Free"),
    "null_deref": ("CWE-476", "NULL Pointer Dereference"),
    "dangerous_import": ("CWE-676", "Use of Potentially Dangerous Function"),
    "dangerous_entitlement": ("CWE-250", "Execution with Unnecessary Privileges"),
    "missing_protection": ("CWE-693", "Protection Mechanism Failure"),
    "command_injection": ("CWE-78", "OS Command Injection"),
    "path_traversal": ("CWE-22", "Path Traversal"),
    "xss": ("CWE-79", "Cross-site Scripting"),
    "sqli": ("CWE-89", "SQL Injection"),
    "type_confusion": ("CWE-843", "Access of Resource Using Incompatible Type"),
    "heap_overflow": ("CWE-122", "Heap-based Buffer Overflow"),
    "stack_overflow": ("CWE-121", "Stack-based Buffer Overflow"),
    "uninitialized": ("CWE-908", "Use of Uninitialized Resource"),
    "info_leak": ("CWE-200", "Exposure of Sensitive Information"),
}


def estimate_cvss(severity, attack_vector):
    """Estimate CVSS score from severity and attack vector."""
    key = (severity.lower(), attack_vector.lower())
    return CVSS_TABLE.get(key, CVSS_TABLE.get((severity.lower(), "unknown"), 3.3))


def register(subparsers):
    p = subparsers.add_parser("report", help="Generate vulnerability report")
    p.add_argument("binary", nargs="?", default=None, help="Target binary path")
    p.add_argument("--from-audit", type=str, default=None, metavar="FILE_OR_DASH",
                   help="Audit JSON output (file path or '-' for stdin)")
    p.add_argument("--title", type=str, default="Security Assessment Report",
                   help="Report title")
    p.add_argument("--author", type=str, default="CatByte Toolkit",
                   help="Report author")
    p.add_argument("--template", choices=["bugbounty", "internal", "brief"],
                   default="internal", help="Report format template")
    p.add_argument("--markdown", action="store_true",
                   help="Output raw Markdown instead of JSON")
    p.add_argument("--html", action="store_true",
                   help="Output standalone HTML report")
    add_output_args(p)
    p.set_defaults(func=run)


def run(args):
    out = make_formatter(args)

    # Collect findings
    audit_data = _collect_findings(args, out)
    if audit_data is None:
        out.emit({"error": "No audit data available. Use --from-audit or pipe from cb audit."}, "report")
        return

    # Extract binary path
    binary = args.binary or audit_data.get("binary", audit_data.get("target", "unknown"))

    # Enrich findings with CVSS estimates
    findings = _extract_findings(audit_data)
    if not findings:
        out.emit({"error": "No findings to report."}, "report")
        return

    findings = _enrich_findings(findings)

    # Sort by severity (high first)
    sev_order = {"high": 0, "medium": 1, "low": 2, "unknown": 3}
    findings.sort(key=lambda f: (sev_order.get(f.get("severity", "unknown"), 3),
                                  -f.get("cvss", 0)))

    # Build report
    report = _build_report(binary, findings, args)

    # Render markdown
    markdown = _render_markdown(report, args.template)
    report["markdown"] = markdown

    # Render HTML if requested
    if getattr(args, "html", False):
        html = _render_html(report, args.template)
        report["html"] = html
        print(html)
    elif args.markdown:
        print(markdown)
    else:
        out.emit(report, "report")


def _collect_findings(args, out):
    """Load audit data from file, stdin, or run audit."""
    from_audit = getattr(args, "from_audit", None)

    if from_audit:
        if from_audit == "-":
            data = load_piped_input()
            if data:
                return data
        else:
            try:
                with open(from_audit) as f:
                    return json.load(f)
            except (json.JSONDecodeError, OSError) as e:
                out.status(f"Warning: Failed to load audit data: {e}")
                return None

    # Try piped input
    if not sys.stdin.isatty():
        try:
            text = sys.stdin.read()
            if text.strip():
                return json.loads(text)
        except (json.JSONDecodeError, Exception):
            pass

    return None


def _extract_findings(audit_data):
    """Extract findings from audit data into a flat list."""
    findings = []

    sections = audit_data.get("sections", {})

    # From vuln section
    vuln = sections.get("vuln", {})
    for f in vuln.get("dangerous_imports", []):
        ftype = "dangerous_import"
        cwe_id, cwe_name = CWE_MAP.get(ftype, ("", ""))
        findings.append({
            "type": ftype,
            "severity": f.get("risk", "medium"),
            "description": f.get("description", f.get("import", "")),
            "source": "vuln",
            "detail": f,
            "cwe": f.get("cwe", cwe_id),
            "cwe_name": f.get("cwe_name", cwe_name),
        })
    for f in vuln.get("findings", []):
        ftype = f.get("category", "unknown")
        cwe_id, cwe_name = CWE_MAP.get(ftype, ("", ""))
        findings.append({
            "type": ftype,
            "severity": f.get("severity", "medium"),
            "description": f.get("description", ""),
            "source": "vuln",
            "detail": f,
            "cwe": f.get("cwe", cwe_id),
            "cwe_name": f.get("cwe_name", cwe_name),
        })

    # From attack section
    attack = sections.get("attack", {})
    for ent in attack.get("entitlements", {}).get("dangerous", []):
        ftype = "dangerous_entitlement"
        cwe_id, cwe_name = CWE_MAP.get(ftype, ("", ""))
        findings.append({
            "type": ftype,
            "severity": ent.get("risk", "medium"),
            "description": ent.get("description", ent.get("entitlement", "")),
            "source": "attack",
            "detail": ent,
            "cwe": ent.get("cwe", cwe_id),
            "cwe_name": ent.get("cwe_name", cwe_name),
        })

    # From triage protections
    triage = sections.get("triage", {})
    protections = triage.get("protections", {})
    mp_cwe, mp_cwe_name = CWE_MAP.get("missing_protection", ("", ""))
    if protections.get("pie") is False:
        findings.append({
            "type": "missing_protection",
            "severity": "medium",
            "description": "Binary is not position-independent (no PIE)",
            "source": "triage",
            "cwe": mp_cwe,
            "cwe_name": mp_cwe_name,
        })
    if protections.get("stack_canary") is False:
        findings.append({
            "type": "missing_protection",
            "severity": "medium",
            "description": "No stack canary detected",
            "source": "triage",
            "cwe": mp_cwe,
            "cwe_name": mp_cwe_name,
        })

    # From audit summary if present
    summary = audit_data.get("summary", {})
    for f in summary.get("top_findings", []):
        # Avoid duplicates
        desc = f.get("description", "")
        if not any(existing["description"] == desc for existing in findings):
            ftype = f.get("type", "unknown")
            cwe_id, cwe_name = CWE_MAP.get(ftype, ("", ""))
            findings.append({
                "type": ftype,
                "severity": f.get("severity", "medium"),
                "description": desc,
                "source": "audit",
                "detail": f,
                "cwe": f.get("cwe", cwe_id),
                "cwe_name": f.get("cwe_name", cwe_name),
            })

    return findings


def _enrich_findings(findings):
    """Add CVSS estimates to findings."""
    for f in findings:
        severity = f.get("severity", "medium")
        vector = f.get("detail", {}).get("attack_vector", "unknown")
        f["cvss"] = estimate_cvss(severity, vector)
    return findings


def _build_report(binary, findings, args):
    """Build structured report dict."""
    max_cvss = max((f["cvss"] for f in findings), default=0)
    high_count = sum(1 for f in findings if f.get("severity") == "high")
    med_count = sum(1 for f in findings if f.get("severity") == "medium")
    low_count = sum(1 for f in findings if f.get("severity") == "low")

    if high_count > 0:
        risk_level = "high"
    elif med_count > 0:
        risk_level = "medium"
    else:
        risk_level = "low"

    executive_summary = (
        f"Security assessment of `{os.path.basename(binary)}` identified "
        f"{len(findings)} findings: {high_count} high, {med_count} medium, "
        f"{low_count} low severity. "
        f"Maximum estimated CVSS score: {max_cvss}."
    )

    recommendations = []
    if high_count > 0:
        recommendations.append("Address all high-severity findings before deployment")
    if any(f["type"] == "dangerous_import" for f in findings):
        recommendations.append("Replace dangerous C functions with bounded alternatives")
    if any(f["type"] == "missing_protection" for f in findings):
        recommendations.append("Enable all compiler security mitigations (PIE, stack canaries)")
    if any(f["type"] == "dangerous_entitlement" for f in findings):
        recommendations.append("Review and minimize entitlements to least-privilege set")
    if not recommendations:
        recommendations.append("Continue monitoring for new vulnerability patterns")

    return {
        "title": args.title,
        "date": time.strftime("%Y-%m-%d"),
        "author": args.author,
        "binary": binary,
        "executive_summary": executive_summary,
        "risk_level": risk_level,
        "max_cvss": max_cvss,
        "findings_count": {
            "total": len(findings),
            "high": high_count,
            "medium": med_count,
            "low": low_count,
        },
        "findings": findings,
        "recommendations": recommendations,
    }


def _cwe_label(finding):
    """Format CWE as 'CWE-XXX (Name)' or empty string."""
    cwe = finding.get("cwe", "")
    name = finding.get("cwe_name", "")
    if cwe and name:
        return f"{cwe} ({name})"
    if cwe:
        return cwe
    return ""


def _cwe_summary(findings):
    """Collect unique CWE labels from findings."""
    seen = []
    for f in findings:
        label = _cwe_label(f)
        if label and label not in seen:
            seen.append(label)
    return " / ".join(seen) if seen else "N/A"


def _build_attack_chain(findings):
    """Build attack chain section from high-severity findings."""
    high = [f for f in findings if f.get("severity") == "high"]
    if not high:
        return "No high-severity attack chain identified."
    lines = []
    for i, f in enumerate(high, 1):
        cwe = _cwe_label(f)
        cwe_part = f" [{cwe}]" if cwe else ""
        lines.append(f"{i}. **{f['type']}**{cwe_part} — {f.get('description', '')}")
    if len(high) >= 2:
        chain = " → ".join(f["type"] for f in high)
        lines.insert(0, f"**Chain:** {chain}\n")
    return "\n".join(lines)


def _build_root_cause(findings):
    """Build root cause section from findings with detail data."""
    parts = []
    for f in findings:
        detail = f.get("detail", {})
        # Include file/line references if available
        file_ref = detail.get("file", "")
        line_ref = detail.get("line", "")
        func_ref = detail.get("function", detail.get("import", ""))
        if not func_ref:
            continue
        loc = ""
        if file_ref:
            loc = f"`{file_ref}"
            if line_ref:
                loc += f":{line_ref}"
            loc += "` — "
        cwe = _cwe_label(f)
        cwe_part = f" ({cwe})" if cwe else ""
        parts.append(f"- **{func_ref}**{cwe_part}: {loc}{f.get('description', '')}")
    return "\n".join(parts) if parts else "See findings above for root cause details."


def _render_markdown(report, template_name):
    """Render report as Markdown using specified template."""
    findings = report["findings"]
    binary = report["binary"]

    # Build common sections
    findings_section = ""
    for i, f in enumerate(findings, 1):
        cwe = _cwe_label(f)
        cwe_line = f"- **CWE:** {cwe}\n" if cwe else ""
        findings_section += (
            f"### Finding {i}: {f['type']}\n"
            f"- **Severity:** {f.get('severity', 'unknown')}\n"
            f"- **CVSS:** {f.get('cvss', 'N/A')}\n"
            f"{cwe_line}"
            f"- **Description:** {f.get('description', '')}\n"
            f"- **Source:** {f.get('source', 'unknown')}\n\n"
        )

    findings_table = ""
    for i, f in enumerate(findings, 1):
        cwe = f.get("cwe", "")
        findings_table += (
            f"| {i} | {f['type']} | {f.get('severity', '?')} | "
            f"{f.get('cvss', 'N/A')} | {cwe} | {f.get('description', '')[:80]} |\n"
        )

    findings_brief = ""
    for i, f in enumerate(findings, 1):
        findings_brief += (
            f"{i}. **[{f.get('severity', '?').upper()}]** "
            f"{f.get('description', '')} (CVSS {f.get('cvss', 'N/A')})\n"
        )

    impact_section = ""
    high_findings = [f for f in findings if f.get("severity") == "high"]
    if high_findings:
        impact_section = (
            f"This binary has {len(high_findings)} high-severity findings "
            f"that may allow code execution or privilege escalation."
        )
    else:
        impact_section = "No critical impact findings identified."

    recommendations_section = "\n".join(
        f"- {r}" for r in report["recommendations"]
    )

    # Steps to reproduce (numbered, with actual cb commands)
    steps_lines = [
        f"1. Install CatByte Toolkit: `pip install catbyte-toolkit`",
        f"2. Run full audit: `cb audit {binary}`",
        f"3. Review findings in JSON output",
    ]
    for i, f in enumerate(high_findings, 4):
        steps_lines.append(f"{i}. Verify **{f['type']}**: `cb vuln {binary} --category {f['type']}`")
    steps_section = "\n".join(steps_lines)

    cwe_sum = _cwe_summary(findings)
    attack_chain_section = _build_attack_chain(findings)
    root_cause_section = _build_root_cause(findings)

    ctx = {
        "title": report["title"],
        "date": report["date"],
        "author": report["author"],
        "binary": binary,
        "executive_summary": report["executive_summary"],
        "risk_level": report["risk_level"],
        "risk_level_upper": report["risk_level"].upper(),
        "cvss": report["max_cvss"],
        "max_cvss": report["max_cvss"],
        "cwe_summary": cwe_sum,
        "findings_section": findings_section,
        "findings_table": findings_table,
        "findings_detail": findings_section,
        "findings_brief": findings_brief,
        "impact_section": impact_section,
        "recommendations_section": recommendations_section,
        "steps_section": steps_section,
        "attack_chain_section": attack_chain_section,
        "root_cause_section": root_cause_section,
    }

    templates = {
        "bugbounty": TEMPLATE_BUGBOUNTY,
        "internal": TEMPLATE_INTERNAL,
        "brief": TEMPLATE_BRIEF,
    }

    template = templates.get(template_name, TEMPLATE_INTERNAL)
    return template.format(**ctx)


def _html_escape(text):
    """Escape HTML special characters to prevent XSS."""
    if not isinstance(text, str):
        text = str(text)
    return (text
            .replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace('"', "&quot;")
            .replace("'", "&#x27;"))


def _build_chart_svg(findings_count):
    """Build an SVG bar chart showing findings distribution by severity."""
    high = findings_count.get("high", 0)
    medium = findings_count.get("medium", 0)
    low = findings_count.get("low", 0)
    total = high + medium + low
    if total == 0:
        return '<svg width="400" height="60"><text x="10" y="30" font-size="14">No findings</text></svg>'

    bar_width = 300
    bar_height = 30
    colors = {"High": "#e74c3c", "Medium": "#e67e22", "Low": "#27ae60"}
    parts = [("High", high), ("Medium", medium), ("Low", low)]

    bars = []
    x = 50
    for label, count in parts:
        if count == 0:
            continue
        w = max(1, int((count / total) * bar_width))
        bars.append(
            f'<rect x="{x}" y="10" width="{w}" height="{bar_height}" '
            f'fill="{colors[label]}" rx="3"/>'
            f'<text x="{x + w // 2}" y="30" text-anchor="middle" '
            f'fill="white" font-size="12" font-weight="bold">'
            f'{label}: {count}</text>'
        )
        x += w

    svg_width = x + 20
    return (f'<svg width="{svg_width}" height="50" xmlns="http://www.w3.org/2000/svg">'
            + "".join(bars) + "</svg>")


def _render_html(report, template_name):
    """Render report as standalone HTML using specified template."""
    findings = report["findings"]
    findings_count = report["findings_count"]

    # Build findings HTML cards (with CWE)
    findings_html_parts = []
    for i, f in enumerate(findings, 1):
        sev = _html_escape(f.get("severity", "unknown"))
        cwe = _cwe_label(f)
        cwe_part = f'<p><strong>CWE:</strong> {_html_escape(cwe)}</p>' if cwe else ""
        findings_html_parts.append(
            f'<div class="finding-card">'
            f'<h3>Finding {i}: {_html_escape(f["type"])}</h3>'
            f'<p><span class="severity-{sev}">{sev.upper()}</span> '
            f'CVSS: <strong>{_html_escape(str(f.get("cvss", "N/A")))}</strong></p>'
            f'{cwe_part}'
            f'<p>{_html_escape(f.get("description", ""))}</p>'
            f'<p><em>Source: {_html_escape(f.get("source", "unknown"))}</em></p>'
            f'</div>'
        )
    findings_html = "\n".join(findings_html_parts)

    # Build findings table rows (with CWE column)
    table_rows = []
    for i, f in enumerate(findings, 1):
        sev = _html_escape(f.get("severity", "unknown"))
        cwe = _html_escape(f.get("cwe", ""))
        table_rows.append(
            f'<tr><td>{i}</td><td>{_html_escape(f["type"])}</td>'
            f'<td><span class="severity-{sev}">{sev.upper()}</span></td>'
            f'<td>{_html_escape(str(f.get("cvss", "N/A")))}</td>'
            f'<td>{cwe}</td>'
            f'<td>{_html_escape(f.get("description", "")[:80])}</td></tr>'
        )
    findings_table_html = "\n".join(table_rows)

    # Brief findings list
    brief_parts = []
    for i, f in enumerate(findings, 1):
        sev = _html_escape(f.get("severity", "unknown"))
        brief_parts.append(
            f'<li><span class="severity-{sev}">{sev.upper()}</span> '
            f'{_html_escape(f.get("description", ""))} '
            f'(CVSS {_html_escape(str(f.get("cvss", "N/A")))})</li>'
        )
    findings_brief_html = "\n".join(brief_parts)

    # Impact section
    high_findings = [f for f in findings if f.get("severity") == "high"]
    if high_findings:
        impact_section = _html_escape(
            f"This binary has {len(high_findings)} high-severity findings "
            f"that may allow code execution or privilege escalation."
        )
    else:
        impact_section = _html_escape("No critical impact findings identified.")

    # Recommendations
    recommendations_html = "\n".join(
        f"<li>{_html_escape(r)}</li>" for r in report["recommendations"]
    )

    # Chart SVG
    chart_svg = _build_chart_svg(findings_count)

    # Attack chain HTML
    attack_chain_html = _html_escape(_build_attack_chain(findings))

    # Root cause HTML
    root_cause_html = _html_escape(_build_root_cause(findings))

    # Steps HTML
    binary = report["binary"]
    steps_items = [
        f"<li>Install CatByte Toolkit: <code>pip install catbyte-toolkit</code></li>",
        f"<li>Run full audit: <code>cb audit {_html_escape(binary)}</code></li>",
        f"<li>Review findings in JSON output</li>",
    ]
    for f in high_findings:
        steps_items.append(
            f"<li>Verify <strong>{_html_escape(f['type'])}</strong>: "
            f"<code>cb vuln {_html_escape(binary)} --category {_html_escape(f['type'])}</code></li>"
        )
    steps_html = "\n".join(steps_items)

    # CWE summary
    cwe_sum = _html_escape(_cwe_summary(findings))

    ctx = {
        "title": _html_escape(report["title"]),
        "date": _html_escape(report["date"]),
        "author": _html_escape(report["author"]),
        "binary": _html_escape(report["binary"]),
        "executive_summary": _html_escape(report["executive_summary"]),
        "risk_level": _html_escape(report["risk_level"]),
        "risk_level_upper": _html_escape(report["risk_level"].upper()),
        "max_cvss": _html_escape(str(report["max_cvss"])),
        "high_count": findings_count.get("high", 0),
        "med_count": findings_count.get("medium", 0),
        "low_count": findings_count.get("low", 0),
        "style": _HTML_STYLE,
        "chart_svg": chart_svg,
        "findings_html": findings_html,
        "findings_table_html": findings_table_html,
        "findings_brief_html": findings_brief_html,
        "impact_section": impact_section,
        "recommendations_html": recommendations_html,
        "attack_chain_html": attack_chain_html,
        "root_cause_html": root_cause_html,
        "steps_html": steps_html,
        "cwe_summary": cwe_sum,
    }

    html_templates = {
        "bugbounty": HTML_BUGBOUNTY,
        "internal": HTML_INTERNAL,
        "brief": HTML_BRIEF,
    }

    template = html_templates.get(template_name, HTML_INTERNAL)
    return template.format(**ctx)


def main():
    parser = argparse.ArgumentParser(prog="cbreport",
                                     description="Vulnerability report generator")
    parser.add_argument("binary", nargs="?", default=None)
    parser.add_argument("--from-audit", type=str, default=None)
    parser.add_argument("--title", type=str, default="Security Assessment Report")
    parser.add_argument("--author", type=str, default="CatByte Toolkit")
    parser.add_argument("--template", choices=["bugbounty", "internal", "brief"],
                        default="internal")
    parser.add_argument("--markdown", action="store_true")
    parser.add_argument("--html", action="store_true")
    add_output_args(parser)
    args = parser.parse_args()
    run(args)
